import { z } from 'zod'

export const campanhaSchema = z.object({
  titulo: z.string().min(1, 'Título obrigatório'),
  objetivo: z.string().optional(),
  eixoD8: z.string().optional(),
  eixoDm: z.string().optional(),
  al: z.string().optional(),
  trimestre: z.string().optional(),
  dataInicio: z.string().optional(),
  dataFim: z.string().optional(),
  coordenador: z.string().optional(),
  comissao: z.string().optional(),
  membrosComissao: z.string().optional(),
  associadosPresentes: z.string().optional(),
  qtdAssociadosPresentes: z.coerce.number().int().min(0).optional(),
  preLeoPresentes: z.string().optional(),
  qtdPreLeoPresentes: z.coerce.number().int().min(0).optional(),
  amigosConselheirosPresentes: z.string().optional(),
  qtdAmigosConselheirosPresentes: z.coerce.number().int().min(0).optional(),
  pessoasImpactadas: z.coerce.number().int().min(0).optional(),
  custoCampanha: z.coerce.number().min(0).optional(),
  companheirosLeoesPresentes: z.coerce.number().int().min(0).optional(),
  horasTrabalhadasPorPessoa: z.coerce.number().min(0).optional(),
  horasTotaisTrabalhadas: z.coerce.number().min(0).optional(),
  descricaoCampanha: z.string().optional(),
  descricaoHtml: z.string().optional(),
  fotoOficialUrl: z.string().optional(),
  videoUrl: z.string().optional(),
  outrasFotosUrl: z.string().optional(),
  temParceria: z.boolean().optional(),
  entidadeParceira: z.string().optional(),
  tipoParceria: z.string().optional(),
  descricaoParceria: z.string().optional(),
  divulgacao: z.string().optional(),
  pontosMelhorar: z.string().optional(),
  feedback: z.string().optional(),
  localRealizacao: z.string().optional(),
})

export type CampanhaFormData = z.infer<typeof campanhaSchema>
